In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sqlalchemy import create_engine
import urllib

plt.style.use("ggplot")

Sql Server Connection

In [8]:
server = "LAPTOP-71G1NMQR\\SQLEXPRESS"
database = "OTT_DB"

params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 18 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

print("SQL Server Connected Successfully")

SQL Server Connected Successfully

In [10]:
movies = pd.read_sql("SELECT * FROM final_movies", engine)
tvshows = pd.read_sql("SELECT * FROM final_tvshows", engine)

print(movies.head())
print(tvshows.head())

   show_id   type                                        title  \
0      189  Movie                 Sin City: A Dame to Kill For
1     1771  Movie           Captain America: The First Avenger
2     1865  Movie  Pirates of the Caribbean: On Stranger Tides
3     1930  Movie                       The Amazing Spider-Man
4     4258  Movie                                Scary Movie 5

                         director  \
0  Frank Miller, Robert Rodriguez
1                    Joe Johnston
2                    Rob Marshall
3                       Marc Webb
4                  Malcolm D. Lee

                                        cast_members  \
0  Jessica Alba, Bruce Willis, Mickey Rourke, Jos...
1  Chris Evans, Hayley Atwell, Sebastian Stan, To...
2  Johnny Depp, Pen├⌐lope Cruz, Geoffrey Rush, Ia...
3  Andrew Garfield, Emma Stone, Rhys Ifans, Denis...
4  Ashley Tisdale, Simon Rex, Charlie Sheen, Grac...

                                    country  date_added  release_year  rating  \
0                  United States of America  2014-08-20          2014    6.39
1                  United States of America  2011-07-22          2011    7.00
2  United Kingdom, United States of America  2011-05-15          2011    6.56
3                  United States of America  2012-06-23          2012    6.70
4                  United States of America  2013-04-11          2013    4.80

  duration                              genres language  \
0     None             Crime, Action, Thriller       en
1     None  Action, Adventure, Science Fiction       en
2     None          Adventure, Action, Fantasy       en
3     None  Action, Adventure, Science Fiction       en
4     None                              Comedy       en

                                         description  popularity  vote_count  \
0  Some of Sin City's most hard-boiled citizens c...      46.711        3882
1  During World War II, Steve Rogers is a sickly ...      83.313       21654
2  Captain Jack Sparrow crosses paths with a woma...     102.748       14166
3  Peter Parker is an outcast high schooler aband...      77.777       17552
4  Home with their newly-formed family, happy par...      45.980        2824

   vote_average     budget     revenue
0          6.39   65000000    39407616
1          7.00  140000000   370569774
2          6.56  379000000  1046721266
3          6.70  215000000   757930663
4          4.80   20000000    78378744
   show_id     type              title      director  \
0      767  TV Show  Ready Steady Cook  Julian Smith
1      877  TV Show            Caprica           NaN
2     1399  TV Show    Game of Thrones           NaN
3     1401  TV Show     Hell on Wheels           NaN
4     1402  TV Show   The Walking Dead           NaN

                                        cast_members  \
0                                        Rylan Clark
1  Eric Stoltz, Esai Morales, Paula Malcomson, Al...
2  Peter Dinklage, Kit Harington, Nikolaj Coster-...
3  Anson Mount, Colm Meaney, Robin McLeavy, Chris...
4  Lauren Cohan, Norman Reedus, Jeffrey Dean Morg...

                                            country  date_added  release_year  \
0                                    United Kingdom  2020-03-02          2020
1                          United States of America  2010-01-22          2010
2          United Kingdom, United States of America  2011-04-17          2011
3  Canada, United Kingdom, United States of America  2011-11-06          2011
4                          United States of America  2010-10-31          2010

   rating   duration                                       genres language  \
0     6.0  1 Seasons                                      Unknown       en
1     6.9  1 Seasons                      Drama, Sci-Fi & Fantasy       en
2     8.5  1 Seasons  Sci-Fi & Fantasy, Drama, Action & Adventure       en
3     7.6  1 Seasons           Action & Adventure, Drama, Western       en
4     8.1  1 Seasons  Action & Adventure, Drama, Sci-Fi & Fantasy       en

                                         description  popularity  vote_count  \
0  Rylan Clark-Neal puts the next generation of c...      16.778           1
1  Set 58 years before Battlestar Galactica, Capr...      35.596         364
2  Seven noble families fight for control of the ...     812.157       24664
3  The epic story of post-Civil War America, focu...     119.632         422
4  Sheriff's deputy Rick Grimes awakens from a co...     485.660       16790

   vote_average
0           6.0
1           6.9
2           8.5
3           7.6
4           8.1

In [11]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       16000 non-null  int64
 1   type          16000 non-null  str
 2   title         16000 non-null  str
 3   director      15868 non-null  str
 4   cast_members  15796 non-null  str
 5   country       16000 non-null  str
 6   date_added    16000 non-null  object
 7   release_year  16000 non-null  int64
 8   rating        16000 non-null  float64
 9   duration      0 non-null      object
 10  genres        16000 non-null  str
 11  language      16000 non-null  str
 12  description   16000 non-null  str
 13  popularity    16000 non-null  float64
 14  vote_count    16000 non-null  int64
 15  vote_average  16000 non-null  float64
 16  budget        16000 non-null  int64
 17  revenue       16000 non-null  int64
dtypes: float64(3), int64(5), object(2), str(8)
memory usage: 2.2+ MB

In [12]:
tvshows.info()

<class 'pandas.DataFrame'>
RangeIndex: 15991 entries, 0 to 15990
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       15991 non-null  int64
 1   type          15991 non-null  str
 2   title         15991 non-null  str
 3   director      5031 non-null   str
 4   cast_members  14835 non-null  str
 5   country       15991 non-null  str
 6   date_added    15991 non-null  object
 7   release_year  15991 non-null  int64
 8   rating        15991 non-null  float64
 9   duration      15991 non-null  str
 10  genres        15991 non-null  str
 11  language      15991 non-null  str
 12  description   15991 non-null  str
 13  popularity    15991 non-null  float64
 14  vote_count    15991 non-null  int64
 15  vote_average  15991 non-null  float64
dtypes: float64(3), int64(3), object(1), str(9)
memory usage: 2.0+ MB

In [17]:
##datatyp check
tvshows.dtypes

show_id           int64
type                str
title               str
director            str
cast_members        str
country             str
date_added       object
release_year      int64
rating          float64
duration            str
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
dtype: object

In [18]:
##chek dttype
movies.dtypes

show_id           int64
type                str
title               str
director            str
cast_members        str
country             str
date_added       object
release_year      int64
rating          float64
duration         object
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
budget            int64
revenue           int64
dtype: object

In [19]:
##Convert Date Column
movies["date_added"] = pd.to_datetime(
    movies["date_added"],
    dayfirst=True,
    errors="coerce"
)

tvshows["date_added"] = pd.to_datetime(
    tvshows["date_added"],
    dayfirst=True,
    errors="coerce"
)

In [20]:
##check
tvshows.dtypes

show_id                 int64
type                      str
title                     str
director                  str
cast_members              str
country                   str
date_added      datetime64[s]
release_year            int64
rating                float64
duration                  str
genres                    str
language                  str
description               str
popularity            float64
vote_count              int64
vote_average          float64
dtype: object

In [21]:
movies.dtypes

show_id                 int64
type                      str
title                     str
director                  str
cast_members              str
country                   str
date_added      datetime64[s]
release_year            int64
rating                float64
duration               object
genres                    str
language                  str
description               str
popularity            float64
vote_count              int64
vote_average          float64
budget                  int64
revenue                 int64
dtype: object

                    EDA PART

In [22]:
##Dataset Overview
print("Movies Shape:", movies.shape)
print("TV Shows Shape:", tvshows.shape)

Movies Shape: (16000, 18)
TV Shows Shape: (15991, 16)

In [30]:
movies.head()

,show_id,type,title,director,cast_members,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,189,Movie,Sin City: A Dame to Kill For,"Frank Miller, Robert Rodriguez","Jessica Alba, Bruce Willis, Mickey Rourke, Jos...",United States of America,2014-08-20,2014,6.39,None,"Crime, Action, Thriller",en,Some of Sin City's most hard-boiled citizens c...,46.711,3882,6.39,65000000,39407616
1,1771,Movie,Captain America: The First Avenger,Joe Johnston,"Chris Evans, Hayley Atwell, Sebastian Stan, To...",United States of America,2011-07-22,2011,7.00,None,"Action, Adventure, Science Fiction",en,"During World War II, Steve Rogers is a sickly ...",83.313,21654,7.00,140000000,370569774
2,1865,Movie,Pirates of the Caribbean: On Stranger Tides,Rob Marshall,"Johnny Depp, Pen├⌐lope Cruz, Geoffrey Rush, Ia...","United Kingdom, United States of America",2011-05-15,2011,6.56,None,"Adventure, Action, Fantasy",en,Captain Jack Sparrow crosses paths with a woma...,102.748,14166,6.56,379000000,1046721266
3,1930,Movie,The Amazing Spider-Man,Marc Webb,"Andrew Garfield, Emma Stone, Rhys Ifans, Denis...",United States of America,2012-06-23,2012,6.70,None,"Action, Adventure, Science Fiction",en,Peter Parker is an outcast high schooler aband...,77.777,17552,6.70,215000000,757930663
4,4258,Movie,Scary Movie 5,Malcolm D. Lee,"Ashley Tisdale, Simon Rex, Charlie Sheen, Grac...",United States of America,2013-04-11,2013,4.80,None,Comedy,en,"Home with their newly-formed family, happy par...",45.980,2824,4.80,20000000,78378744

In [31]:
tvshows.head()

,show_id,type,title,director,cast_members,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,767,TV Show,Ready Steady Cook,Julian Smith,Rylan Clark,United Kingdom,2020-03-02,2020,6.0,1 Seasons,Unknown,en,Rylan Clark-Neal puts the next generation of c...,16.778,1,6.0
1,877,TV Show,Caprica,NaN,"Eric Stoltz, Esai Morales, Paula Malcomson, Al...",United States of America,2010-01-22,2010,6.9,1 Seasons,"Drama, Sci-Fi & Fantasy",en,"Set 58 years before Battlestar Galactica, Capr...",35.596,364,6.9
2,1399,TV Show,Game of Thrones,NaN,"Peter Dinklage, Kit Harington, Nikolaj Coster-...","United Kingdom, United States of America",2011-04-17,2011,8.5,1 Seasons,"Sci-Fi & Fantasy, Drama, Action & Adventure",en,Seven noble families fight for control of the ...,812.157,24664,8.5
3,1401,TV Show,Hell on Wheels,NaN,"Anson Mount, Colm Meaney, Robin McLeavy, Chris...","Canada, United Kingdom, United States of America",2011-11-06,2011,7.6,1 Seasons,"Action & Adventure, Drama, Western",en,"The epic story of post-Civil War America, focu...",119.632,422,7.6
4,1402,TV Show,The Walking Dead,NaN,"Lauren Cohan, Norman Reedus, Jeffrey Dean Morg...",United States of America,2010-10-31,2010,8.1,1 Seasons,"Action & Adventure, Drama, Sci-Fi & Fantasy",en,Sheriff's deputy Rick Grimes awakens from a co...,485.660,16790,8.1

Statistical Summary

In [27]:
##Numeric Columns Distribution
movies[["rating","popularity","vote_count","vote_average","budget","revenue"]].describe().round(2)

,rating,popularity,vote_count,vote_average,budget,revenue
count,16000.00,16000.00,16000.00,16000.00,1.600000e+04,1.600000e+04
mean,5.96,20.38,718.66,5.96,8.766792e+06,2.446308e+07
std,1.75,68.61,2080.20,1.75,2.912450e+07,1.116977e+08
min,0.00,3.86,0.00,0.00,0.000000e+00,0.000000e+00
25%,5.60,7.84,53.00,5.60,0.000000e+00,0.000000e+00
50%,6.30,10.91,138.00,6.30,0.000000e+00,0.000000e+00
75%,6.92,17.34,422.00,6.92,2.200000e+06,1.654473e+06
max,10.00,3876.01,37119.00,10.00,4.600000e+08,2.799439e+09

In [29]:
tvshows[["rating","popularity","vote_count","vote_average"]].describe()

             rating    popularity    vote_count  vote_average
count  15991.000000  15991.000000  15991.000000  15991.000000
mean       5.419738     64.878246    107.074479      5.419738
std        3.265152    139.421744    607.627216      3.265152
min        0.000000      2.323000      0.000000      0.000000
25%        2.800000     24.898000      1.000000      2.800000
50%        6.800000     36.200000      4.000000      6.800000
75%        7.800000     62.217000     30.000000      7.800000
max       10.000000   6421.923000  24664.000000     10.000000

Unique Values

In [32]:
movies.nunique()

show_id         16000
type                1
title           15485
director         9508
cast_members    15639
country          1464
date_added       4423
release_year       16
rating            490
duration            0
genres           2769
language           74
description     15855
popularity      11173
vote_count       2693
vote_average      490
budget            958
revenue          5327
dtype: int64

In [33]:
tvshows.nunique()

show_id         15991
type                1
title           15668
director         3808
cast_members    14628
country           565
date_added       4899
release_year       16
rating            397
duration            1
genres           1218
language           71
description     12783
popularity      14323
vote_count       1021
vote_average      397
dtype: int64

In [67]:
# ==============================
# TV Shows KPI Summary
# ==============================

print("Total TV Shows :", tvshows.shape[0])
print("Total Columns :", tvshows.shape[1])

print("Unique Titles :", tvshows["title"].nunique())
print("Unique Directors :", tvshows["director"].nunique())
print("Unique Countries :", tvshows["country"].nunique())
print("Unique Languages :", tvshows["language"].nunique())
print("Unique Genres :", tvshows["genres"].nunique())

print("Average Rating :", round(tvshows["rating"].mean(),2))
print("Average Popularity :", round(tvshows["popularity"].mean(),2))
print("Average Vote Count :", round(tvshows["vote_count"].mean(),2))

print("Highest Rated TV Show :", tvshows.loc[tvshows["rating"].idxmax(),"title"])
print("Most Popular TV Show :", tvshows.loc[tvshows["popularity"].idxmax(),"title"])

Total TV Shows : 15991
Total Columns : 16
Unique Titles : 15668
Unique Directors : 3808
Unique Countries : 565
Unique Languages : 71
Unique Genres : 1218
Average Rating : 5.42
Average Popularity : 64.88
Average Vote Count : 107.07
Highest Rated TV Show : Endless Love
Most Popular TV Show : The Late Show with Stephen Colbert

In [68]:
# ==============================
# Movies KPI Summary
# ==============================

print("Total Movies :", movies.shape[0])
print("Total Columns :", movies.shape[1])

print("Unique Titles :", movies["title"].nunique())
print("Unique Directors :", movies["director"].nunique())
print("Unique Countries :", movies["country"].nunique())
print("Unique Languages :", movies["language"].nunique())
print("Unique Genres :", movies["genres"].nunique())

print("Average Rating :", round(movies["rating"].mean(),2))
print("Average Popularity :", round(movies["popularity"].mean(),2))
print("Average Vote Count :", round(movies["vote_count"].mean(),2))
print("Average Revenue :", round(movies["revenue"].mean(),2))
print("Average Budget :", round(movies["budget"].mean(),2))

print("Highest Rated Movie :", movies.loc[movies["rating"].idxmax(),"title"])
print("Most Popular Movie :", movies.loc[movies["popularity"].idxmax(),"title"])
print("Highest Revenue Movie :", movies.loc[movies["revenue"].idxmax(),"title"])
print("Highest Budget Movie :", movies.loc[movies["budget"].idxmax(),"title"])

Total Movies : 16000
Total Columns : 18
Unique Titles : 15485
Unique Directors : 9508
Unique Countries : 1464
Unique Languages : 74
Unique Genres : 2769
Average Rating : 5.96
Average Popularity : 20.38
Average Vote Count : 718.66
Average Revenue : 24463075.66
Average Budget : 8766791.71
Highest Rated Movie : The Photographer
Most Popular Movie : The Gorge
Highest Revenue Movie : Avengers: Endgame
Highest Budget Movie : Avatar: The Way of Water

Top 10 Languages

In [34]:
movies["language"].value_counts().head(10)

language
en    9534
fr    1054
ja     904
ko     876
es     731
zh     378
it     312
hi     290
de     279
ru     190
Name: count, dtype: int64

In [35]:
tvshows["language"].value_counts().head(10)

language
en    4435
zh    2456
ja    1880
ko    1364
es     915
fr     585
de     451
tl     398
pt     346
hi     345
Name: count, dtype: int64

Top 10 geners

In [36]:
movies["genres"].value_counts().head(10)

genres
Drama               1336
Comedy               776
Documentary          587
Drama, Romance       473
Horror               391
Comedy, Drama        389
Horror, Thriller     356
Comedy, Romance      242
Romance              232
Romance, Drama       230
Name: count, dtype: int64

In [37]:
tvshows["genres"].value_counts().head(10)

genres
Drama                2743
Reality              1104
Comedy               1067
Unknown               973
Comedy, Drama         516
Documentary           464
Drama, Comedy         399
Talk                  328
Animation, Comedy     311
Drama, Crime          241
Name: count, dtype: int64

Top 10 Countries

In [38]:
movies["country"].value_counts().head(10)

country
United States of America                    5421
Japan                                        845
South Korea                                  789
France                                       612
United Kingdom                               581
Unknown                                      466
India                                        419
United Kingdom, United States of America     401
Canada                                       348
Canada, United States of America             338
Name: count, dtype: int64

In [39]:
tvshows["country"].value_counts().head(10)

country
United States of America    2339
China                       1797
Unknown                     1795
Japan                       1740
South Korea                 1210
United Kingdom               524
Canada                       389
Philippines                  386
Germany                      375
India                        352
Name: count, dtype: int64

In [40]:
###Release Year Analysis
movies["release_year"].value_counts().sort_index()

release_year
2010    1000
2011    1000
2012    1000
2013    1000
2014    1000
2015    1000
2016    1000
2017    1000
2018    1000
2019    1000
2020    1000
2021    1000
2022    1000
2023    1000
2024    1000
2025    1000
Name: count, dtype: int64

In [41]:
tvshows["release_year"].value_counts().sort_index()

release_year
2010    1000
2011    1000
2012    1000
2013    1000
2014    1000
2015    1000
2016    1000
2017    1000
2018    1000
2019    1000
2020    1000
2021    1000
2022    1000
2023    1000
2024    1000
2025     991
Name: count, dtype: int64

Highest rating of movies and tvshows

In [46]:
movies.nlargest(10, "rating")[["title","rating","release_year"]]

                                     title  rating  release_year
7978                      The Photographer    10.0          2017
8867                                    It    10.0          2017
9576    In├ício Garapa, Um Matuto Sonhador    10.0          2010
9665                Youthful Mother-in-law    10.0          2018
11292  Secret Night Of Mother And Daughter    10.0          2020
11329              Sincheon Station Exit 3    10.0          2020
11348                   Nice Sister-In-Law    10.0          2019
11554               Three Sisters Swapping    10.0          2019
11576              Actresses: Sex Audition    10.0          2020
12159                         The Shepherd    10.0          2020

In [44]:
tvshows.nlargest(10, "rating")[["title","rating","release_year"]]

                               title  rating  release_year
119                     Endless Love    10.0          2010
283              Journey to the West    10.0          2012
293              Journey to the West    10.0          2010
336          Pyaar Kii Ye Ek Kahaani    10.0          2010
370                  AI Football GGO    10.0          2010
381                             Daam    10.0          2010
389         Mongo Wrestling Alliance    10.0          2011
495                         Hallo K3    10.0          2010
522  Sun, Sex and Suspicious Parents    10.0          2011
541                          Twisted    10.0          2010

Most Popular  movies and tvshows

In [48]:
movies.nlargest(10, "popularity")[["title","popularity"]].round(2)

                                  title  popularity
13297                         The Gorge     3876.01
14452                       Flight Risk     3320.62
11911             Mufasa: The Lion King     2643.63
13208              Sonic the Hedgehog 3     2402.50
15070                           Moana 2     2347.01
13104                            Amaran     1780.29
12385  Captain America: Brave New World     1495.72
14238                         Companion     1283.36
14670                        Panda Plan     1214.51
9512                  Kraven the Hunter     1195.88

In [49]:
tvshows.nlargest(10, "popularity")[["title","popularity"]].round(2)

                                        title  popularity
3182       The Late Show with Stephen Colbert     6421.92
2358   The Tonight Show Starring Jimmy Fallon     4925.25
3534                    Good Mythical Morning     3414.47
6010                    Chronicles of the Sun     2987.48
15033                          Volta por Cima     2885.72
15032                           She's the One     2862.87
14060                         Crazy About You     2442.24
14228         La Casa de los Famosos Colombia     2398.16
2742              Late Night with Seth Meyers     2395.02
6629                                  GH d├║o     2379.88

In [54]:
##Highest Revenue (Movies Only)
movies.nlargest(10, "revenue")[["title","revenue","release_year"]]

                              title     revenue  release_year
5261              Avengers: Endgame  2799439100          2019
1645       Avatar: The Way of Water  2320250281          2022
2989   Star Wars: The Force Awakens  2068223624          2015
5262         Avengers: Infinity War  2052415039          2018
13506                      Ne Zha 2  1990000000          2025
10745       Spider-Man: No Way Home  1921847111          2021
13842                  Inside Out 2  1698863816          2024
2884                 Jurassic World  1671537444          2015
7479                  The Lion King  1662020819          2019
66                     The Avengers  1518815515          2012

In [53]:
##Highest Budget (Movies Only)
movies.nlargest(10, "budget")[["title","budget","release_year"]]

                                             title     budget  release_year
1645                      Avatar: The Way of Water  460000000          2022
3486              Star Wars: The Rise of Skywalker  416000000          2019
1924                          Avatar: Fire and Ash  400000000          2025
9955     Mission: Impossible - The Final Reckoning  400000000          2025
10797            Ant-Man and the Wasp: Quantumania  388369742          2023
2      Pirates of the Caribbean: On Stranger Tides  379000000          2011
2298                       Avengers: Age of Ultron  365000000          2015
5261                             Avengers: Endgame  356000000          2019
6819                                        Fast X  340000000          2023
12033                           The Electric State  320000000          2025

In [61]:
##Average Rating by Language MOVIES
movies.groupby("language")["rating"].mean().sort_values(
    ascending=False
).head(10).round(2)

language
si    7.80
gl    7.50
dz    7.40
ga    7.28
mk    7.22
zu    7.20
la    7.10
ro    7.02
kk    6.90
et    6.88
Name: rating, dtype: float64

In [62]:
##TV Shows
tvshows.groupby("language")["rating"].mean().sort_values(
    ascending=False
).head(10).round(2)

language
zu    10.00
az     9.20
mk     9.00
as     8.00
ur     7.13
ro     7.07
is     7.00
it     6.87
af     6.70
ta     6.63
Name: rating, dtype: float64

In [64]:
##Average Popularity by Country
##Movies
movies.groupby("country")["popularity"].mean().sort_values(
    ascending=False
).head(10).round(2)

country
Belgium, France, Latvia                                               632.71
United States of America, Japan                                       626.89
St. Kitts and Nevis                                                   624.84
United Kingdom, France, United States of America, Japan               571.33
Japan, New Zealand, United States of America                          442.25
Denmark, United Kingdom, Thailand                                     310.37
Belgium, France, United States of America, Mexico                     281.42
Australia, United Kingdom, United States of America, China, Cyprus    263.61
United States of America, Netherlands                                 246.18
United Kingdom, Germany, Italy                                        206.12
Name: popularity, dtype: float64

In [66]:
##TV Shows
tvshows.groupby("country")["popularity"].mean().sort_values(
    ascending=False
).head(10).round(2)

country
Mexico, United States of America, Colombia                              647.91
United States of America, Singapore                                     616.86
United States of America, United Kingdom, Malaysia                      583.65
United Kingdom, United States of America, Germany, Ireland, Sweden      561.08
France, Japan, South Korea                                              512.44
Japan, South Korea, United States of America                            488.88
United States of America, Ireland                                       423.72
Canada, Denmark, Singapore, United Kingdom, United States of America    418.56
India, Singapore                                                        385.28
Belgium, France, Switzerland                                            318.68
Name: popularity, dtype: float64

1. Correlation Matrix (Movies)

In [55]:
movies[["rating","popularity","vote_count","vote_average","budget","revenue"]].corr().round(2)

              rating  popularity  vote_count  vote_average  budget  revenue
rating          1.00        0.07        0.17          1.00    0.10     0.12
popularity      0.07        1.00        0.16          0.07    0.22     0.22
vote_count      0.17        0.16        1.00          0.17    0.67     0.75
vote_average    1.00        0.07        0.17          1.00    0.10     0.12
budget          0.10        0.22        0.67          0.10    1.00     0.75
revenue         0.12        0.22        0.75          0.12    0.75     1.00

Movies – Overall Conclusion
Strong positive relationships exist between Budget and Revenue (0.75).
Vote Count and Revenue (0.75) also show a strong positive relationship.
Movie ratings have little influence on popularity or revenue.
Rating and Vote Average are duplicate metrics and one can be excluded from further analysis.

2. Correlation Matrix (TV Shows)

In [56]:
tvshows[["rating","popularity","vote_count","vote_average"]].corr().round(2)

              rating  popularity  vote_count  vote_average
rating          1.00        0.05        0.13          1.00
popularity      0.05        1.00        0.15          0.05
vote_count      0.13        0.15        1.00          0.13
vote_average    1.00        0.05        0.13          1.00

TV Shows – Overall Conclusion
No strong correlations were found among the TV show metrics.
The only perfect correlation is between Rating and Vote Average, indicating duplicate information.
Popularity and Vote Count have only a weak positive relationship.
Ratings are not strong predictors of popularity or audience engagement.

Final Business Insight
The Movies dataset shows meaningful business relationships, particularly between Budget, Revenue, and Vote Count, making these variables valuable for performance analysis. In contrast, the TV Shows dataset exhibits mostly weak relationships, suggesting that popularity and ratings alone are not sufficient to explain overall TV show performance.

In [70]:
# Save Movies CSV
movies.to_csv("movies.csv", index=False)

# Save TV Shows CSV
tvshows.to_csv("tvshows.csv", index=False)

print("Both CSV files saved successfully.")

Both CSV files saved successfully.